version: '2'
services:
  db:
    restart: always
    image: mysql:5.7
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=rails
    - MYSQL_USER=rails
    - MYSQL_PASSWORD=rails
    - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - "8081:80"
